//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputSystem/MarioActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MarioActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MarioActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MarioActions"",
    ""maps"": [
        {
            ""name"": ""gamplay"",
            ""id"": ""c16890cf-9e92-40a8-88e2-82acf36624f9"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""c7789212-3891-4ee1-802e-91e02a8cc724"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""movevertical"",
                    ""type"": ""Value"",
                    ""id"": ""284f4554-0872-4326-9bed-b5153f34b793"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""aimlook"",
                    ""type"": ""Value"",
                    ""id"": ""047be507-cce9-47e1-ab2f-ef9b693295a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""a309bc65-bf0e-417c-b0a3-dac19734e008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jumphold"",
                    ""type"": ""Button"",
                    ""id"": ""6a578387-6068-4ef2-8627-c0e554578245"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fire"",
                    ""type"": ""Button"",
                    ""id"": ""7067d32c-dec2-4c9b-bc14-074bab30b896"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""firepoint"",
                    ""type"": ""Value"",
                    ""id"": ""4346d1e2-2b60-44e2-822f-5cbbe9d001bb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""altfire"",
                    ""type"": ""Value"",
                    ""id"": ""88eb8aab-dc8d-4858-86be-b67c2eca8d52"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9129d17d-bfc3-44fa-ac80-602c022d1779"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0c94e5bd-4dfb-4615-9000-c0ea4fa676c9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""20a55fb9-9649-433a-8cc8-bacf05d91b81"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4358f17a-a456-43d9-9465-e47c926e6ef0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KB&M"",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26dd2567-198c-4c4b-9509-1e12843e20a3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold(duration=0.3)"",
                    ""processors"": """",
                    ""groups"": ""KB&M"",
                    ""action"": ""jumphold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74efa5c0-1ce2-476c-8457-113e5dac908c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB&M"",
                    ""action"": ""aimlook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a6c0037-90a2-4e88-9baf-c912f1c41efa"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB&M"",
                    ""action"": ""fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""68520c56-0776-4831-898a-4c9219ba66ee"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""firepoint"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""58ed0497-6c5c-4b2b-9a68-d8bb0b0bd466"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""firepoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d2e6c235-dbaa-46d0-a5c7-c40f0e340fd0"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""firepoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""55b51963-422c-4bb6-8400-7850c04ead6c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""altfire"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9baded42-0dd7-4265-ad17-481fd51669da"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""altfire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0d177cfd-cf32-41a3-b072-f53e4e122750"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KB&M"",
                    ""action"": ""altfire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""aa4434af-4d7d-4421-802b-55468a75bd1c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movevertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2ac9a150-943a-49a3-80fc-c27fe28f3181"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movevertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""474fc70b-5ea7-4421-bc6f-436313945975"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movevertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KB&M"",
            ""bindingGroup"": ""KB&M"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // gamplay
        m_gamplay = asset.FindActionMap("gamplay", throwIfNotFound: true);
        m_gamplay_move = m_gamplay.FindAction("move", throwIfNotFound: true);
        m_gamplay_movevertical = m_gamplay.FindAction("movevertical", throwIfNotFound: true);
        m_gamplay_aimlook = m_gamplay.FindAction("aimlook", throwIfNotFound: true);
        m_gamplay_jump = m_gamplay.FindAction("jump", throwIfNotFound: true);
        m_gamplay_jumphold = m_gamplay.FindAction("jumphold", throwIfNotFound: true);
        m_gamplay_fire = m_gamplay.FindAction("fire", throwIfNotFound: true);
        m_gamplay_firepoint = m_gamplay.FindAction("firepoint", throwIfNotFound: true);
        m_gamplay_altfire = m_gamplay.FindAction("altfire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gamplay
    private readonly InputActionMap m_gamplay;
    private List<IGamplayActions> m_GamplayActionsCallbackInterfaces = new List<IGamplayActions>();
    private readonly InputAction m_gamplay_move;
    private readonly InputAction m_gamplay_movevertical;
    private readonly InputAction m_gamplay_aimlook;
    private readonly InputAction m_gamplay_jump;
    private readonly InputAction m_gamplay_jumphold;
    private readonly InputAction m_gamplay_fire;
    private readonly InputAction m_gamplay_firepoint;
    private readonly InputAction m_gamplay_altfire;
    public struct GamplayActions
    {
        private @MarioActions m_Wrapper;
        public GamplayActions(@MarioActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_gamplay_move;
        public InputAction @movevertical => m_Wrapper.m_gamplay_movevertical;
        public InputAction @aimlook => m_Wrapper.m_gamplay_aimlook;
        public InputAction @jump => m_Wrapper.m_gamplay_jump;
        public InputAction @jumphold => m_Wrapper.m_gamplay_jumphold;
        public InputAction @fire => m_Wrapper.m_gamplay_fire;
        public InputAction @firepoint => m_Wrapper.m_gamplay_firepoint;
        public InputAction @altfire => m_Wrapper.m_gamplay_altfire;
        public InputActionMap Get() { return m_Wrapper.m_gamplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamplayActions set) { return set.Get(); }
        public void AddCallbacks(IGamplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamplayActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @movevertical.started += instance.OnMovevertical;
            @movevertical.performed += instance.OnMovevertical;
            @movevertical.canceled += instance.OnMovevertical;
            @aimlook.started += instance.OnAimlook;
            @aimlook.performed += instance.OnAimlook;
            @aimlook.canceled += instance.OnAimlook;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @jumphold.started += instance.OnJumphold;
            @jumphold.performed += instance.OnJumphold;
            @jumphold.canceled += instance.OnJumphold;
            @fire.started += instance.OnFire;
            @fire.performed += instance.OnFire;
            @fire.canceled += instance.OnFire;
            @firepoint.started += instance.OnFirepoint;
            @firepoint.performed += instance.OnFirepoint;
            @firepoint.canceled += instance.OnFirepoint;
            @altfire.started += instance.OnAltfire;
            @altfire.performed += instance.OnAltfire;
            @altfire.canceled += instance.OnAltfire;
        }

        private void UnregisterCallbacks(IGamplayActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @movevertical.started -= instance.OnMovevertical;
            @movevertical.performed -= instance.OnMovevertical;
            @movevertical.canceled -= instance.OnMovevertical;
            @aimlook.started -= instance.OnAimlook;
            @aimlook.performed -= instance.OnAimlook;
            @aimlook.canceled -= instance.OnAimlook;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @jumphold.started -= instance.OnJumphold;
            @jumphold.performed -= instance.OnJumphold;
            @jumphold.canceled -= instance.OnJumphold;
            @fire.started -= instance.OnFire;
            @fire.performed -= instance.OnFire;
            @fire.canceled -= instance.OnFire;
            @firepoint.started -= instance.OnFirepoint;
            @firepoint.performed -= instance.OnFirepoint;
            @firepoint.canceled -= instance.OnFirepoint;
            @altfire.started -= instance.OnAltfire;
            @altfire.performed -= instance.OnAltfire;
            @altfire.canceled -= instance.OnAltfire;
        }

        public void RemoveCallbacks(IGamplayActions instance)
        {
            if (m_Wrapper.m_GamplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamplayActions @gamplay => new GamplayActions(this);
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KB&M");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    public interface IGamplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMovevertical(InputAction.CallbackContext context);
        void OnAimlook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJumphold(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnFirepoint(InputAction.CallbackContext context);
        void OnAltfire(InputAction.CallbackContext context);
    }
}
